### ISSUE TITLE
Changing the distribution and index types in existing snapshots don't have any effect

### ISSUE THREAD

**Issue by sdebruyn** [dbt-msft/dbt-synapse#132]
If you have a snapshot table with a certain distribution and/or index type and you change one of those later on through a config, nothing happens.

However, these cannot be changed after the table was created so we'd have to drop them and recreate the table. This is also something we'd probably not want to do since in the case of snapshots, we would have data loss.

**Comment by dataders** [comment]
should this trigger a full-refresh? what's the behavior on dbt-postgres
