### ISSUE TITLE
Stand up new CI-testing pool

### ISSUE THREAD

**Issue by dataders** [dbt-msft/dbt-synapse#149]
I've shut down the Azure subscription that was hosting our infrastructure for both dbt-sqlserver and dbt-synapse. The reason being that it was on my personal credit card.

Given the forthcoming 1.4.0 releases for both adapters, it's a requirement that we can run these integration tests against the required changes.

The GitHub Action workflows are still defined and configured properly, the remaining work is:
1. Make a new RG that contains:
  1. A Synapse workspace
  2. An Azure SQL Server
  3. AAD: ~4 user accounts and a service principal that have full access to the above
2. Modify the secrets of this repository and dbt-sqlserver to point to the new values

**Comment by prdpsvs** [comment]
@dataders, completed this in 1.4.0 upgrade - https://github.com/microsoft/dbt-synapse/pull/171
