### ISSUE TITLE
 dbt-synapse `1.8.0rc1` broken by dbt-fabric `1.8.3`

### ISSUE THREAD

**Issue by dataders** [dbt-msft/dbt-synapse#242]
https://github.com/microsoft/dbt-fabric/pull/156 modified the below macros to include a `USE [database]`, which is not compatible with Azure Synapse:
- `fabric__list_relations_without_caching`
- `fabric__get_relation_without_caching`
- `fabric__drop_relation_script`

Because the latest dbt-synapse (`1.8.0rc1`) dependency is compatibility pinned (`~=`) to `1.8.0rc1`, it auto-picks up any new patches to `1.8`, including the latest `1.8.3` which includes the changes in https://github.com/microsoft/dbt-fabric/pull/156

https://github.com/microsoft/dbt-synapse/blob/8f4a6a3ab82ea20652bc162b0acbaee461702445/setup.py#L19

**Comment by prdpsvs** [comment]
@dataders , The synapse adapter has overrides for above macros in PR https://github.com/microsoft/dbt-synapse/pull/245/. Why are tests throwing the error - https://github.com/microsoft/dbt-synapse/actions/runs/9155466561/job/25168215613?

Did I miss something?

**Comment by amychen1776** [comment]
@prdpsvs was this resolved?

**Comment by prdpsvs** [comment]
@amychen1776 , yes
