### ISSUE TITLE
SQLAuth does not work in 1.8

### ISSUE THREAD

**Issue by dataders** [dbt-msft/dbt-synapse#250]
After dbt-synapse began to inhierit from dbt-fabric instead of dbt-sqlserver, SQLAuth was effectively removed from this adapter as it isn't supported within Fabric and therefore dbt-fabric.
 
#218 was opened to flag this. #225, opened to solve this issue was only merged to the `v1.7.latest` branch so that it could be backported. However, the `master` branch still is missing the old ConnectionManager class that #225 added.

You can see the difference in the files below:
- [`master`'s `synapse_connection_manager.py`](https://github.com/microsoft/dbt-synapse/blob/master/dbt/adapters/synapse/synapse_connection_manager.py)
- [`1.7.latest`'s `synapse_connection_manager.py`](https://github.com/microsoft/dbt-synapse/blob/v1.7.latest/dbt/adapters/synapse/synapse_connection_manager.py)

**Comment by amychen1776** [comment]
@prdpsvs would it be possible to get the fix merged into 1.8+? This is breaking several implementations.

**Comment by prdpsvs** [comment]
@amychen1776 , @dataders , This is addressed in 1.8.1
