### ISSUE TITLE
Issues with tests when `generate_schema_name()` is defined and users don't have access to create the `target.schema` schema

### ISSUE THREAD

**Issue by b-per** [dbt-msft/dbt-synapse#259]
The [code for `tests/helpers.sql` ](https://github.com/microsoft/dbt-synapse/blob/4a34961d08cafaea916f1216ef2dc042e6b59104/dbt/include/synapse/macros/materializations/tests/helpers.sql#L3C2-L7C6) tries to create the schema `target.schema` when running the test if it doesn't exist.

Some people don't have access to create schemas in the DW and customize `generate_schema_name()` and `generate_alias_name()` to match to their requirements.

For those folks all tests are failing if they don't have access to create `target.schema`.

Removing the following code made the tests working for tests not starting with `with`.
```
  IF NOT EXISTS (SELECT * FROM sys.schemas WHERE name = '{{ target.schema }}')
  BEGIN
    EXEC('CREATE SCHEMA [{{ target.schema }}]')
  END
```

Then, for tests started with `with`, as nested CTEs are not supported, the code creates a view `{{ target.schema }}.testview_{{ range(1300, 19000) | random }}`. This fails as well for people who don't have access to create their schema.

It would be great to use the logic of `generate_schema_name()` (and maybe `generate_alias_name()`) for figuring out where the view needs to be created.

**Comment by amychen1776** [comment]
@prdpsvs could you take a look on this one?
