### ISSUE TITLE
Cannot create tables out of SQL Select statements 

### ISSUE THREAD

**Issue by Rahul-Gajula** [dbt-msft/dbt-synapse#68]
1) I am interested to know what data types for the table creation the DBT-Synapse support. 
2) Attached are the screenshots of the error what was captured while doing the runs

![image](https://user-images.githubusercontent.com/92009794/140954903-d30d4da0-54aa-4ba3-b575-1b198fa27e6a.png)
![image](https://user-images.githubusercontent.com/92009794/140955272-df512526-ec09-4b4c-a64a-fcf7323bb388.png)

Out of all this I was able to generate the views from the select SQL statements against the database, but not the tables. 
Note: Under dbt.project.yml i clearly defined the materialization as table to perform the action.

**Comment by dataders** [comment]
what type of Azure synapse dedicated pools are you using: dedicated or serverless? My guess is you're using a serverless pool which do not support tables. You may want to try [dbt-msft/dbt-synapse-serverless](https://github.com/dbt-msft/dbt-synapse-serverless) instead. Though huge caveat that serverless pools aren't that great of a solution for synapse today.

**Comment by Rahul-Gajula** [comment]
Hi swanderz , could not reply you immediately. 
I am using a dedicated SQL pool. No luck with table creation. 
![image](https://user-images.githubusercontent.com/92009794/141049906-db2599ca-d49a-4663-b719-1d176579bf22.png)

**Comment by dataders** [comment]
weird! here's some questions:

1. what version of `dbt-synapse` are you using?
1. are you using seeds or sources for these transformations?
2. what is the column type of `device_id`?
3. can you share the info from the latest run in the log (`logs/dbt.log`)?

**Comment by Rahul-Gajula** [comment]
1)  - sqlserver: 0.20.1
     - synapse: 0.20.0

2) Sources yes 
![image](https://user-images.githubusercontent.com/92009794/141086700-818d0724-049b-40b9-8631-763250cd232f.png)

3) 
![image](https://user-images.githubusercontent.com/92009794/141087023-f26e9d19-e1e2-4c85-88d2-c2291ee903a4.png)
![image](https://user-images.githubusercontent.com/92009794/141087125-c76fbd24-5276-4c64-af44-497be7b8a1c7.png)
![image](https://user-images.githubusercontent.com/92009794/141087493-fc859472-b189-4b42-aeb7-dd84690e5141.png)
![image](https://user-images.githubusercontent.com/92009794/141087594-30a25880-6a2a-4b73-87b3-cbb9245ee9aa.png)

4) [dbt.log](https://github.com/dbt-msft/dbt-synapse/files/7511403/dbt.log)

**Comment by alieus** [comment]
Thanks @Rahul-Gajula. I’ll try to repro this error and see what I find

**Comment by dataders** [comment]
Looking at the error message I see:

> Database error: ('42000', "[42000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]The statement failed. Column 'device_id' has a data type that cannot participate in a columnstore index.

Any chance you can change your column types to not use `nvarchar(max)`? Not only will it not work with dbt-synapse, but it's not a good idea as it isn't very optimized.

**Comment by alieus** [comment]
@swanderz  you're absolutely right. Running this directly in Synapse validates that you cannot have nvarchar(max) as a datatype:
![image](https://user-images.githubusercontent.com/45928849/141177613-a35a6e33-22fa-470f-9684-d19035ada814.png)

However, the below works with no errors:
![image](https://user-images.githubusercontent.com/45928849/141177764-2915105f-fcf0-44dc-afaa-d4b658a2fcc5.png)

**Comment by Rahul-Gajula** [comment]
Hi alieus and swanderz, 

Tried creating table as per the comments. Failed yet again. 

![image](https://user-images.githubusercontent.com/92009794/141401698-9b567cda-6d8c-468a-a0a7-50012f4d2325.png)

[dbt.log](https://github.com/dbt-msft/dbt-synapse/files/7524582/dbt.log)

It's not even recognizing the Create Syntax

**Comment by alieus** [comment]
Hey @Rahul-Gajula , if you’d like to test this, you’d have to run it directly in your synapse workspace. 

What you need to do is change the datatypes in your source tables from nvarchar(max) to nvarchar(n) and then run your select queries again in dbt.

**Comment by Rahul-Gajula** [comment]
Hi alieus, 

Even with the data type nvarchar(n) i am not able to create a table. 

CREATE TABLE telemetry_test(
  device_id NVARCHAR(n),
  IP_adress NVARCHAR(n)
);

**Comment by alieus** [comment]
where n is the size of the string in byte-pairs.  For example, nvarchar(16).

**Comment by Rahul-Gajula** [comment]
Hi alieus, 

Even that i tried. refer to the screen shot. 
![image](https://user-images.githubusercontent.com/92009794/141409478-78cde503-6dd7-49f7-9674-00a65ead70df.png)

**Comment by Rahul-Gajula** [comment]
Hi alieus and swanderz,

i figured out the solution for it. i need to change my data type to make it work. Using convert operator in the sql syntax worked. 

![image](https://user-images.githubusercontent.com/92009794/143464552-09660a61-1cf0-4e69-a446-ead5d4c8350e.png)

Thank you for your kind help. you may close the ticket.

**Comment by dataders** [comment]
Glad to hear it! I’m sure this issue will definitely help someone else in the future.
