### ISSUE TITLE
running pip install dbt-synapse==0.18.1 gives success but the plugin isn't really installed

### ISSUE THREAD

**Issue by BeatrizSTavares** [dbt-msft/dbt-synapse#73]
![image](https://user-images.githubusercontent.com/25089450/146581219-071924d1-451d-41a4-bfed-f81c6c5112c2.png)
![image](https://user-images.githubusercontent.com/25089450/146581307-8d05f582-b30f-4579-a49e-9c280dcde222.png)

Dbt debug doesn't find any adapter type synapse.

**Comment by dataders** [comment]
@BeatrizSTavares thanks for reporting! have you gotten dbt-synapse to work before? does this only happen with `0.18.1`? what version of Python are you using?

**Comment by BeatrizSTavares** [comment]
@swanderz Yes I have gotten to work before, with version 0.21.0. The python version I'm using is 3.8.10. I saw here https://github.com/dbt-msft/dbt-synapse that it only has the support needed for version 0.18.0, so I needed to use this version

**Comment by dataders** [comment]
Try version 0.21! The readme is out of date

**Comment by BeatrizSTavares** [comment]
@swanderz I tried with 0.21 dbt version (synapse as well) and I can't reference one model from another, for instance referencing an ephemeral from a table model. The compiled code gives me an error about nested with's (CTE's).

**Comment by dataders** [comment]
Ah! Ephemeral isn't supported w dbt-synapse unfortunately. Please [vote on this idea](https://feedback.azure.com/d365community/idea/ae896b78-7c37-ec11-a819-000d3ae2b306) so it may be supported!

**Comment by BeatrizSTavares** [comment]
Ok, thank you!
