### ISSUE TITLE
"anders are you there??" printout when running dbt test

### ISSUE THREAD

**Issue by acb14js** [dbt-msft/dbt-synapse#77]
Hi there, 

I'm getting the string "anders are you there??" printed out when running dbt test. I think there is a log left in the code. 

![image](https://user-images.githubusercontent.com/23119769/148951096-d3bc7321-f0d9-48fd-b61e-18f99d951032.png)

I have found this in the manifest.json 

![image](https://user-images.githubusercontent.com/23119769/148951158-0fbc19ea-6bb5-43fb-a66e-6c7c2ed837fb.png)

**Comment by dataders** [comment]
whoops! what version of dbt-synapse are you using?

**Comment by acb14js** [comment]
I'm using 0.21.0

![image](https://user-images.githubusercontent.com/23119769/149034635-bf63a7f8-3bb5-42ba-b2ee-b41fd63d096a.png)

**Comment by sdebruyn** [comment]
fixed in #88
