### ISSUE TITLE
Compilation Error 

### ISSUE THREAD

**Issue by Rahul-Gajula** [dbt-msft/dbt-synapse#78]
Compilation Error
  dbt found two macros named "synapse__get_columns_in_relation" in the project
  "dbt_synapse".
   To fix this error, rename or remove one of the following macros:
      - macros\adapters\columns.sql
      - macros\adapters.sql

Hi Team, when i am doing dbt run or dbt compile in CLI i am seeing this error for synapse profile.

**Comment by Rahul-Gajula** [comment]
attached is the log, i tried renaming the file in the path and even removed the file from the path but nothing worked.
[log.txt](https://github.com/dbt-msft/dbt-synapse/files/8129971/log.txt)

**Comment by swanjson** [comment]
Hi @Rahul-Gajula. What version are you using? I was having a similar issue on 1.0.1 and upgrading to 1.0.2b1 seemed to help. Here's the thread: #75

**Comment by Rahul-Gajula** [comment]
PS F:\DBT\Jinjaandmacro\models\example> dbt run --profiles-dir F:\DBT\Jinjaandmacro --no-version-check --model example
09:32:39  Running with dbt=1.0.3
09:32:39  [WARNING]: Deprecated functionality
The `source-paths` config has been renamed to `model-paths`. Please update your
`dbt_project.yml` configuration to reflect this change.
09:32:39  [WARNING]: Deprecated functionality
The `data-paths` config has been renamed to `seed-paths`. Please update your
`dbt_project.yml` configuration to reflect this change.
09:32:39  Partial parse save file not found. Starting full parse.
09:32:42  Encountered an error:
Compilation Error
  In dispatch: No macro named 'get_columns_in_relation_sql' found
      Searched for: 'jinja.synapse__get_columns_in_relation_sql', 'jinja.sqlserver__get_columns_in_relation_sql', 'jinja.default__get_columns_in_relation_sql', 'audit_helper.synapse__get_columns_in_relation_sql', 'audit_helper.sqlserver__get_columns_in_relation_sql', 'audit_helper.default__get_columns_in_relation_sql'


PS F:\DBT\Jinjaandmacro\models\example> dbt --version
installed version: 1.0.3
   latest version: 1.0.3

Up to date!

Plugins:
  - snowflake: 1.0.0 - Up to date!
  - sqlserver: 1.0.0 - Up to date!
  - synapse: 1.0.2b1 - Update available!
  Your version of dbt-synapse is out of date! You can find instructions for upgrading here:
  https://docs.getdbt.com/dbt-cli/install/overview

Hi Team, 
i updated the plugin to the latest version which is in fact the pre release version, still i am seeing the compilation error

**Comment by jordandakota** [comment]
I am also seeing the compilation error noted above. 

installed version: 1.0.3
   latest version: 1.0.3

Up to date!

Plugins:
  - sqlserver: 1.0.0 - Up to date!
  - synapse: 1.0.1 - Up to date!

19:50:08  Running with dbt=1.0.3
19:50:08  Partial parse save file not found. Starting full parse.
19:50:09  Encountered an error:
Compilation Error
  dbt found two macros named "synapse__get_columns_in_relation" in the project
  "dbt_synapse".
   To fix this error, rename or remove one of the following macros:
      - macros\adapters\columns.sql
      - macros\adapters.sql

dbt debug works fine, only have the example directory in the models directory.

**Comment by dataders** [comment]
closing in favor of #75, which is already resolved
