### ISSUE TITLE
Encountered an error: dbt_sqlserver://macros/adapters.sql

### ISSUE THREAD

**Issue by jordandakota** [dbt-msft/dbt-synapse#80]
Encountering a generic error when running in Linux, works fine on Windows, same setup:

{
    "code": "Z002",
    "data": {
        "e": "'dbt_sqlserver://macros/adapters.sql'"
    },
    "invocation_id": "f68f1432-d313-4ee6-be64-b7dc85b4e863",
    "level": "error",
    "log_version": 1,
    "msg": "Encountered an error:\n'dbt_sqlserver://macros/adapters.sql'",
    "node_info": {},
    "pid": 3687,
    "thread_name": "MainThread",
    "ts": "2022-03-09T01:08:33.663686Z",
    "type": "log_line"
}

dbt version: 1.0.3
python version: 3.9.10
python path: /opt/hostedtoolcache/Python/3.9.10/x64/bin/python
os info: Linux-5.13.0-1014-azure-x86_64-with-glibc2.31
Using profiles.yml file at /home/vsts/.dbt/profiles.yml
Using dbt_project.yml file at /home/vsts/work/1/s/dbt_project.yml
Configuration:
  profiles.yml file [OK found and valid]
  dbt_project.yml file [OK found and valid]

installed version: 1.0.3
latest version: 1.0.3
Up to date!
Plugins:
  - sqlserver: 1.0.0 - Up to date!
  - synapse: 1.0.2b1 - Update available!
  
Debug works fine against the target server, running anything else like docs generate, run, test, compile, just gives me the macros/adapters.sql error and quits. Target is Synapse and using MS ODBC 17.

**Comment by moralescastillo** [comment]
I ran into the same issue when using synapse: 1.0.2b1. I updated to synapse: 1.1.0, and the issue was solved.

**Comment by dataders** [comment]
seems it has to do with an error in the beta version `1.0.2b1` that is now fixed
